backend:
  name: github
  repo: reespace-bit/my-spaces
  branch: main
  site_domain: reespace-bit.github.io

media_folder: "images"
public_folder: "/my-spaces/images"
media_library:
  name: uploadcare
  config:
    publicKey: demopublickey

collections:
  - name: artikel
    label: Artikel
    folder: artikel
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Judul", name: "judul", widget: "string"}
      - {label: "Ringkasan", name: "ringkasan", widget: "string"}
      - {label: "Gambar Cover", name: "cover", widget: "image", required: false}
      - {label: "Kategori", name: "kategori", widget: "select", options: ["HR & Career", "Perspectives", "Journal", "Story"]}
      - {label: "Tanggal", name: "tanggal", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Isi", name: "body", widget: "markdown"}
